# NodeJS Version 20
FROM node:20-buster-slim

# Copiar archivos de la aplicación
COPY . ./app/dailyTrends

# Establecer el directorio de trabajo
WORKDIR /app/dailyTrends

# Instalar paquetes de Node
RUN npm install --legacy-peer-deps

# Exponer el puerto
EXPOSE 3000

# Comando de inicio
CMD ["npm", "run", "start"]
